### ISSUE TITLE
Add json output option

### ISSUE THREAD

**Issue by Seluj78** [Seluj78/Potodo#10]

**Comment by Seluj78** [comment]
Idées en vrac:

`-j` `--json` overwrites the normal output and outputs to json either IN `STDOUT` or in file given on the CLI

This will use another function to process the `.po` files and format that into a dict.

output json example:
```json
{
  "software": "potodo",
  "version": "0.4.0",
  "directories": {
    ".": {
      "completion": 86.7,
      "files": {
        "glossay.po": {
          "translated": 2,
          "untranslated": 3,
          "completion": 66.0,
          "fuzzies": null
        }
      }
    },
    "library": {...}
  }
}
```

**Comment by awecx** [comment]
Je ferai plus un truc :
{
  "software": "potodo",
  "version": "0.4.0",
  "directories": [
     {
      "path": ".",
      "completion": 86.7,
      "files": {
        "glossay.po": {
          "translated": 2,
          "untranslated": 3,
          "completion": 66.0,
          "fuzzies": null
        }
      }
     },
     {
      "path": "library",
      ...
      }
  ]
}

pour itérer plus facilement (et avoir un schema qui ne dépende pas de la structure).

**Comment by Seluj78** [comment]
Ca me va très bien ! 👌

**Comment by awecx** [comment]
Et donc osef de --count quand --json est activée ?
On met le pourcentage ET le nombre.

**Comment by Seluj78** [comment]
> Et donc osef de --count quand --json est activée ?

Ouais clairement

> On met le pourcentage ET le nombre.

En vrai on peux mette beaucoup de choses mais je pense

 - nb pas traduit
 - nb traduit
 - nb fuzzies
 - percent per file
 - percent per folder

ca devrait suffire

**Comment by JulienPalard** [comment]
`--json -` pour stdout, `--json FILE` pour écrire dans le fichier `FILE` ?

**Comment by awecx** [comment]
> `--json -` pour stdout, `--json FILE` pour écrire dans le fichier `FILE` ?

Ou bien `--json` pour stdout et `--json > FILE` pour écrire dans le fichier `FILE` ? :-)

**Comment by Seluj78** [comment]
Les deux me vont 👌

**Comment by JulienPalard** [comment]
Je pense que @awecx a raison. Le `-` c'est surtout pratique quand le comportement par défaut c'est d'écrire dans un fichier, donc peut être typiquement du binaire. Là c'est du texte on peut envoyer sur stdout par défaut, et utiliser une redirection shell pour écrire dans un fichier, en effet.
