### ISSUE TITLE
do not use f-string

### ISSUE THREAD

**Issue by deronnax** [Seluj78/Potodo#17]
Some of our translator still have python 3.5 and then can't use polib. If you don't feel like to do it, I can do it. If so, assign it to me

**Comment by Seluj78** [comment]
😗

**Comment by deronnax** [comment]
same comment than the other issue : I see that the code is dupplicated, would you mind cleaning it a bit before i start working on it 😇 ?

**Comment by Seluj78** [comment]
Yes gogogo 👍 😁

**Comment by Seluj78** [comment]
@deronnax heads up, big PR with big refactor on it's way, so you can work on this once #23 is merged !

**Comment by deronnax** [comment]
yup

**Comment by deronnax** [comment]
Just for the record : Python 3.5 will be end-of-life in September 13, 2020. Also I encountered only one translator stuck with Python 3.5 (but 3.5 is the default Python for the current Debian).
Is this a fight we wanna fight ?

**Comment by awecx** [comment]
Today is June 4th and I have done a PR that uses some f-strings…
Not being able to use modern Python features for only one translator seems too harsh. I say we close this issue.

**Comment by JulienPalard** [comment]
Python 3.5 is no longer the default for current Debian:

- Debian stable (currently Buster) defaults to Python 3.7.3
- Debian testing (currently Bullseye) defaults to Python 3.8.2

As Mariatta would say: « Friends let friends use f-strings » (source: her wallpaper).

It would be nice to add an explicit `python_requires='>=3.6'` in the setup.py file.
