### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by Seluj78** [Seluj78/Potodo#26]

**Comment by deronnax** [comment]
you would a very good strpint subject 😇

**Comment by Seluj78** [comment]
Agreed, let's plan a sprint !

**Comment by awecx** [comment]
Agreed.
Will handle https://github.com/Seluj78/Potodo/issues/10 as a pre-requisite.

**Comment by Seluj78** [comment]
I was thinking of pure unit testing but I like the idea I have with json, idk if it's the same for you ! 🤗

**Comment by JulienPalard** [comment]
Related to https://github.com/Seluj78/Potodo/pull/36 (but not "closes" I wrote a single little shy test)

**Comment by Seluj78** [comment]
@all-contributors please add @Seluj78 for review and code
