### ISSUE TITLE
Add verbose option

### ISSUE THREAD

**Issue by Seluj78** [Seluj78/Potodo#32]

**Comment by JulienPalard** [comment]
I'm not a fan of `-V`, maybe `--verbose` is enough, don't add a short one. I'm grepping in some man files to check if there's a clear concensus on this one.

**Comment by Seluj78** [comment]
Here's the choices for the option(s)

 - `--verbose`
 - `-v --verbose` (conflicts with `-v --version`)
 - `-V --verbose`

**Comment by JulienPalard** [comment]
OK stats are:
```
    384        --version
    246        -V, --version
     70        -v, --version
```

so clearly not `-v` (for verbose). I'd go for the first one: only the long one.

**Comment by Seluj78** [comment]
hahaha but I was mostly right 😁 `--verbose` only it is !

**Comment by JulienPalard** [comment]
Oh, did I messed up between "--verbose" and "--version" as we were on the PR about "--version" I though it was the "--version" issue! (see my stats are about --version, not --verbose).

For version I'm ok with `--version` and `-v`. `-v` is good as we can use it multiple times like `-v` `-vv`, `-vvv`, which is nicely handled by argparse `count` argument.

**Comment by Seluj78** [comment]
for verbose you mean ? `--version` is about to be merged

**Comment by JulienPalard** [comment]
Fixed in the message, it's a mess. It's late for my défense.

**Comment by Seluj78** [comment]
Oh right crap, SIGDODO after verbose is merged and another PR is out
