### ISSUE TITLE
Add travis cache to speedup tox

### ISSUE THREAD

**Issue by Seluj78** [Seluj78/Potodo#40]

**Comment by JulienPalard** [comment]
To cache, ... what?

**Comment by Seluj78** [comment]
> and watch things happening (you must have python2.7 and python3.6 installed in your environment otherwise you will see errors). When you run tox a second time you’ll note that it runs much faster because it keeps track of virtualenv details and will not recreate or re-install dependencies. You also might want to checkout tox configuration and usage examples to get some more ideas.

from https://tox.readthedocs.io/en/latest/

**Comment by JulienPalard** [comment]
YES ! So big I missed it :]

**Comment by Seluj78** [comment]
https://docs.travis-ci.com/user/caching/
